version: 0.3

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t sagemaker-sparkml-serving:2.4 .
    - docker tag sagemaker-sparkml-serving:2.4.3 716469146435.dkr.ecr.us-east-1.amazonaws.com/sagemaker-sparkml-serving:2.4.3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 716469146435.dkr.ecr.us-east-1.amazonaws.com/sagemaker-sparkml-serving:2.4.3
